services:
  node:
    image: node:25-alpine
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    volumes:
      - ./vite.config.js:/usr/src/app/vite.config.js
      - ./pages:/usr/src/app/pages
      - ./public:/usr/src/app/public
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
    ports:
      - "5173:5173"
    networks:
      - dear-net

  nginx:
    depends_on:
      - node
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
