services:
  node:
    image: node:25-alpine
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    volumes:
      - ./.env:/usr/src/app/.env
      - ./vite.config.js:/usr/src/app/vite.config.js
      - ./pages:/usr/src/app/pages
      - ./public:/usr/src/app/public
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
    ports:
      - "5173:5173"
    networks:
      - dear-net
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:5173"]
      interval: 3s
      timeout: 3s
      retries: 10

  nginx:
    depends_on:
      node:
        condition: service_healthy
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
